#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: besu-verkle-trie
  description: An enterprise-grade Java-based, Apache 2.0 licensed Ethereum client https://wiki.hyperledger.org/display/besu
  homepage: https://www.hyperledger.org/projects/besu
  default_branch: main
  has_downloads: false
  has_issues: true
  has_projects: true
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
